name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git version
          ls -hl
          git config --global --add safe.directory /home/runner/work/go-cqhttp/go-cqhttp
          git init /home/runner/work/go-cqhttp/go-cqhttp
          cd /home/runner/work/go-cqhttp/go-cqhttp
          git remote add origin https://github.com/Mrs4s/go-cqhttp
          git config --local gc.auto 0
          git pull origin master

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Checkout Dist
      #  uses: actions/checkout@v2
      #  with:
      #    repository: 'gocq/dist'
      #    ref: master
      #    ssh-key: ${{ secrets.SSH_KEY }}
      #    path: upstream/dist

      #- name: Update Dist
      #  run: |
      #    chmod +x scripts/upload_dist.sh
      #    ./scripts/upload_dist.sh
